### ISSUE TITLE
Add Data for Wyoming

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/OpenHuntingData#108]

**Comment by backpkr1** [comment]
Well Wyoming this far has the best data! Here is more info on all of the files:Wyoming Game & Fish geospatial data has the following general characteristics:
 
Format: 	Esri Shapefile (with a couple of exceptions in file-GDB format)
Zip Utility: 	WinZip
Projection: 	WyLAM (Wyoming Lambert Conformal Conic)
Datum: 	NAD83 (North American 1983; Spheroid GRS 1980)
Extent: 	Statewide, or the full extent of the theme if less than statewide
Metadata Content: 	A prerequisite for automatic distribution of geospatial data

**Comment by backpkr1** [comment]
finished with wyoming available data

**Comment by backpkr1** [comment]
ID: HUNTAREA NAME:HERDUNIT
