### ISSUE TITLE
Add example walkthrough for any state to contributing.md

### ISSUE THREAD

**Issue by andrewljohnson** [OpenBounds/OpenHuntingData#109]
Maybe the next time someone (Kate/Ana?) sources and adds a file via the form, they could document the process for the one file/state...
- chose GitHub issue for state X
- googled for _foo_
- went to Y website where data seemed to be
- eventually found the files at this URL
- downloaded the file, opened in QGIS (maybe more detailed explanation)
- entered information into form and submitted

**Comment by kdough03** [comment]
Are these open for me to work on, then? Is there anything specific I 
should start with, i.e., are the states being divvied up in any way?

On 11/18/2015 11:38 PM, Andrew L. Johnson wrote:
>
> Maybe the next time someone sources and adds a file via the form, they 
> could document the process for the one file/state...
>
>   * chose GitHub issue for state X
>   * googled for /foo/
>   * went to Y website where data seemed to be
>   * eventually found the files at this URL
>   * downloaded the file, opened in QGIS (maybe more detailed explanation)
>   * entered information into form and submitted
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/OpenBounds/OpenHuntingData/issues/109>.
>

-- 
Kate Dougherty
Freelance Science Writer, Researcher, and Geographer
(267) 357-0149 | Skype: kate_dougherty
http://katedoughertywriter.com/
http://www.linkedin.com/in/katedoughertywriter

**Comment by andrewljohnson** [comment]
Come chat in Slack in #gis, ready to start. I'll give you background now, and we can get you started working tomorrow.

**Comment by kdough03** [comment]
No longer needed, since project is almost done?
