### ISSUE TITLE
Add success message when pull request submits

### ISSUE THREAD

**Issue by nathancahill** [OpenBounds/OpenHuntingData#114]

**Comment by kdough03** [comment]
Do you care about projection? I guess these will vary by state.

> On Nov 20, 2015, at 5:49 PM, Nathan Cahill <notifications@github.com> wrote:
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenBounds/OpenHuntingData/issues/114>.
> 

Kate Dougherty
Freelance Science Writer, Researcher, and GIS Technician
http://www.katedoughertywriter.com <http://www.katedoughertywriter.com/>
katedoughertywriter@gmail.com
267-357-0149

**Comment by JesseCrocker** [comment]
closed in favor of https://github.com/OpenBounds/Processing/issues/20
