### ISSUE TITLE
how to deal with open data behind a download app

### ISSUE THREAD

**Issue by smnorris** [OpenBounds/OpenHuntingData#18]
Some jurisdictions have open data, but downloading it may not be scriptable. 
For example, http://catalogue.data.gov.bc.ca/dataset/wildlife-management-units

**Comment by JesseCrocker** [comment]
That's a good point, and one i had not thought of, but im guessing it will come up for a bunch of jurisdictions. Im guessing the easiest way to deal with it will be to setup an S3 bucket, and sources like that will have to have a manual step of someone downloading the data, and uploading it to s3.

If github large file storage worked with forks it would be a great solution for this. But it doesn't.

**Comment by andrewljohnson** [comment]
Shall we close this since it's documented in README now @jessecrocker?

**Comment by JesseCrocker** [comment]
No, I haven't actually made an S3 bucket to put the data in yet.

**Comment by JesseCrocker** [comment]
Data can be put in hunting-data.openbounds.org/source-data/
