### ISSUE TITLE
sources/US/CO/biggamegmuboundaries.json file not found to download

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/OpenHuntingData#252]
INFO:root:Processing sources/US/CO/biggamegmuboundaries.json
INFO:root:Downloading https://gisftp02.state.co.us/cStateLevelAgencies/DNR/CPW/From/2015/GISData/AdministrativeData/CPW_GMUBoundaries.zip
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): gisftp02.state.co.us
/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
ERROR:root:Failed to download https://gisftp02.state.co.us/cStateLevelAgencies/DNR/CPW/From/2015/GISData/AdministrativeData/CPW_GMUBoundaries.zip

**Comment by kdough03** [comment]
Link doesn't work; must be downloaded manually. Will upload to s3.

**Comment by kdough03** [comment]
Resolved by new PR.
