### ISSUE TITLE
sources/US/MN/all.json

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/OpenHuntingData#253]
INFO:root:Processing sources/US/MN/all.json
INFO:root:Downloading ftp://ftp.gisdata.mn.gov/pub/gdrs/data/pub/us_mn_state_dnr/bdry_turkey_permit_areas/shp_bdry_turkey_permit_areas.zip
INFO:root:Reading shp_bdry_turkey_permit_areas.zip
ERROR:root:property TPA_TXT not found in source feature
ERROR:root:Error processing file sources/US/MN/all.json

**Comment by kdough03** [comment]
Replace with new species-specific data.

**Comment by kdough03** [comment]
Replaced with new species-specific data.
