### ISSUE TITLE
sources/US/MN/turkey.json

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/OpenHuntingData#254]
INFO:root:Processing sources/US/MN/turkey.json
INFO:root:Downloading ftp://ftp.gisdata.mn.gov/pub/gdrs/data/pub/us_mn_state_dnr/bdry_turkey_permit_areas/shp_bdry_turkey_permit_areas.zip
INFO:root:Returning ftp://ftp.gisdata.mn.gov/pub/gdrs/data/pub/us_mn_state_dnr/bdry_turkey_permit_areas/shp_bdry_turkey_permit_areas.zip from local cache
INFO:root:Reading shp_bdry_turkey_permit_areas.zip
ERROR:root:property TPA_TXT not found in source feature
ERROR:root:Error processing file sources/US/MN/turkey.json

**Comment by kdough03** [comment]
Resolved.
