### ISSUE TITLE
sources/US/WV/whitetaileddeer.json

### ISSUE THREAD

**Issue by kdough03** [OpenBounds/OpenHuntingData#283]
Only 1 shp in zip, but it generates this error:

![image](https://cloud.githubusercontent.com/assets/15642783/17947079/4b336832-6a08-11e6-9533-2245d71b9991.png)

Code: 

`{
   "name" : "WV White-Tailed Deer Hunting Regulation Splits",
   "url": "https://s3.amazonaws.com/data.openbounds.org/USAHunting/manual-downloads/WV-county-reg-splits.zip",
   "species": [
      "White-Tailed Deer"
   ],
   "attribution": "West Virginia Division of Natural Resources, Wildlife Division",
   "properties": {
      "id": "OBJECTID",
      "name": "NAME"
   },
   "country": "US",
   "state": "WV",
   "filetype": "shp"
}`

**Comment by FishheadNate** [comment]
http://www.wvdnr.gov/Hunting/Regs1819/2018-19_Hunting_Regs.pdf
- pages 20-30

**Comment by FishheadNate** [comment]
boundary line data: http://wvgis.wvu.edu/data/data.php

will take some time to compile the county splits
