### ISSUE TITLE
add special wildlife areas to Alaska hunting map

### ISSUE THREAD

**Issue by BigYellowSun** [OpenBounds/OpenHuntingData#323]
Here is a link to the shapefile from the Alaska Department of Fish and Game for the special wildlife areas within existing Game Management Units.  These are subdivisions of the GMUs for hunting regulations.

http://adfg.maps.arcgis.com/home/item.html?id=67fd162568ed4e3aba27ca504353d878

or http://adfg.maps.arcgis.com/home/index.html

**Comment by FishheadNate** [comment]
AK Special Wildlife Areas were merged into the master by https://github.com/OpenBounds/OpenHuntingData/pull/325
