### ISSUE TITLE
Consider using Github oauth for data submission pull request

### ISSUE THREAD

**Issue by nathancahill** [OpenBounds/OpenHuntingData#33]
Right now the source json is saved to a gist (or copied manually to a pull request). This could all be replaced with an oauth login that submits a pull request from the submission form.

It would involve setting up an oauth application on Github, and about 2 hours of work integrating it on Github pages.

**Comment by nathancahill** [comment]
It turns out this is a much better way to do this (closing the other PR). The one hangup is that a server-side component is needed to hold the app secret. I tested [prose/gatekeeper](https://github.com/prose/gatekeeper) and it worked perfectly as described.

**Comment by JesseCrocker** [comment]
So there are 2 there are 2 things that need to get done for this?
create github app
deploy gatekeeper somewhere

is that right?
Currently all out infrastructure runs on AWS, can we run gatekeeper there instead of on heroku?

**Comment by nathancahill** [comment]
Yep. When you create the app, the OAuth endpoint should be the GH pages url.. http://trailbehind.github.io/OpenHuntingData/

**Comment by nathancahill** [comment]
Gatekeeper is a really simple node app, should be easy to spin up anywhere.

**Comment by nathancahill** [comment]
Closed via #36.
