### ISSUE TITLE
Add data for KS

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/OpenHuntingData#337]
previous attempt https://github.com/OpenBounds/OpenHuntingData/pull/151

**Comment by FishheadNate** [comment]
Missing Wildlife Areas:

- [ ] http://ksoutdoors.com/KDWPT-Info/Locations/Wildlife-Areas/Northwest/Gove-Public-Domain
- [ ] http://ksoutdoors.com/KDWPT-Info/Locations/Wildlife-Areas/Northwest/Keith-Sebelius-Reservoir-Norton
  - Have Dove fields, need WA file
- [ ] http://ksoutdoors.com/KDWPT-Info/Locations/State-Fishing-Lakes/Northwest-Region/Ottawa
- [ ] http://ksoutdoors.com/KDWPT-Info/Locations/Wildlife-Areas/Northwest/Sherman
- [ ] http://ksoutdoors.com/KDWPT-Info/Locations/Wildlife-Areas/Northwest/Smoky-Hill-Kanopolis
- [ ] http://ksoutdoors.com/KDWPT-Info/Locations/Wildlife-Areas/Northeast
  - Have Clinton WA dove fields, need all NE WA files
