### ISSUE TITLE
Add data for MI

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/OpenHuntingData#341]
Previous attempt https://github.com/OpenBounds/OpenHuntingData/pull/174

**Comment by FishheadNate** [comment]
### Still need species specific maps
http://www.michigan.gov/documents/dnr/hunting_and_trapping_digest_461177_7.pdf
- Deer Management Units & Antler Point Restriction map: p32
- Upland Game maps: p44-45

 https://github.com/OpenBounds/OpenHuntingData/pull/373 added the areas open for hunting
