### ISSUE TITLE
Add more data for ND

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/OpenHuntingData#342]
Previous attempt https://github.com/OpenBounds/OpenHuntingData/pull/179
https://github.com/OpenBounds/OpenHuntingData/pull/180
https://github.com/OpenBounds/OpenHuntingData/pull/181
https://github.com/OpenBounds/OpenHuntingData/pull/182
https://github.com/OpenBounds/OpenHuntingData/pull/183
https://github.com/OpenBounds/OpenHuntingData/pull/184
https://github.com/OpenBounds/OpenHuntingData/pull/185
https://github.com/OpenBounds/OpenHuntingData/pull/186
https://github.com/OpenBounds/OpenHuntingData/pull/187
https://github.com/OpenBounds/OpenHuntingData/pull/188
https://github.com/OpenBounds/OpenHuntingData/pull/189
https://github.com/OpenBounds/OpenHuntingData/pull/190
https://github.com/OpenBounds/OpenHuntingData/pull/192
https://github.com/OpenBounds/OpenHuntingData/pull/193
https://github.com/OpenBounds/OpenHuntingData/pull/194
https://github.com/OpenBounds/OpenHuntingData/pull/195
https://github.com/OpenBounds/OpenHuntingData/pull/196

**Comment by FishheadNate** [comment]
Fixed by https://github.com/OpenBounds/OpenHuntingData/pull/393
