### ISSUE TITLE
Add WA deer units

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/OpenHuntingData#343]
Previous attempt https://github.com/OpenBounds/OpenHuntingData/pull/207/files

**Comment by FishheadNate** [comment]
Looks like the deer units are subsets of the GMUs in pull request https://github.com/OpenBounds/OpenHuntingData/pull/345

<img width="200" alt="gohunt" src="https://user-images.githubusercontent.com/22895187/29779906-94a49506-8bd9-11e7-95e7-81a3fc14b61d.png">
<img width="400" alt="gohunt1" src="https://user-images.githubusercontent.com/22895187/29779875-7f1b10c0-8bd9-11e7-9d8c-57f189e39af4.png">

**Comment by JesseCrocker** [comment]
So this data would just be a duplicate and isnt needed?

**Comment by FishheadNate** [comment]
Yes and no, in some places like the Wenaha GMU it would be duplictae data. But around the Spokana area, the Deer Areas appear to be just a section of the GMU.
- [wdfw_regs_pg40-41.pdf](https://github.com/OpenBounds/OpenHuntingData/files/1257353/wdfw_regs_pg40-41.pdf)

**Comment by JesseCrocker** [comment]
So it sounds like this should be it's own layer and we should keep this issue open for now.
