### ISSUE TITLE
The labels on CO GMUs overlay duplicate when zooming

### ISSUE THREAD

**Issue by FishheadNate** [OpenBounds/OpenHuntingData#351]
The labels on the CO GMUs overlay duplicate when zooming in.
- http://www.gaiagps.com/map/?lat=39.129995&lon=-105.747625&zoom=11.5&layer=GaiaTopoRasterFeet,gaiacogmu
![img_0611](https://user-images.githubusercontent.com/22895187/29843964-51f68804-8cd3-11e7-800a-610e2021f99c.PNG)

Also, the labels on this overlay don't line up with the labels on the Colorado Parks & Wildlife's site:
- http://cpw.state.co.us/learn/Maps/BigGameGMUmap.pdf

However, the CO Big Game GMUs overlay looks like the correct source for GMUs.
- http://www.gaiagps.com/map/?lat=39.507499&lon=-105.907237&zoom=6.4&layer=GaiaTopoRasterFeet,US_CO_bear-blackbear-cougar-deer-elk-moose-mountainlion-muledeer-pronghorn-puma-white-taileddeer

**Comment by JesseCrocker** [comment]
That looks like the old raster tiles, not the vector based rendering.

**Comment by JesseCrocker** [comment]
@FishheadNate Can you try removing the source and re-adding it to see if that fixes it.

**Comment by FishheadNate** [comment]
Results of removing & re-adding the layer

gaiagps.com:
- the labels display at 2 different font sizes for about a 1 sec and then correct themselves

iOS:
- labels don't adjust starting at zoom = 10
![img_0635](https://user-images.githubusercontent.com/22895187/30213443-a31792b2-946e-11e7-8b3a-b0be6d096feb.PNG)

Andriod:
- My Android is running slow overall so the label issue may be caused by that
![screenshot sep 8 2017 8-42-05 am](https://user-images.githubusercontent.com/22895187/30214404-f7357c80-9471-11e7-9129-3e492fabf07f.png)

**Comment by JesseCrocker** [comment]
It looks like the problem here is that this is an old source that should have been removed. We have a newer source that replaces it.
Removed.
