### ISSUE TITLE
Add OR Wildlife Areas

### ISSUE THREAD

**Issue by FishheadNate** [OpenBounds/OpenHuntingData#354]
User complained and wants a refund due to lack of labeling:
- https://gaiagpshelp.zendesk.com/agent/tickets/21552

Wildlife Areas:
 - Wildlife Areas: http://www.dfw.state.or.us/resources/visitors/wildlife.asp
 - Walk In Access Areas: http://www.dfw.state.or.us/lands/AH/open_fields/index.asp

**Comment by JesseCrocker** [comment]
Is this data that belongs as it's own layer in the hunting collection, or gets rolled into public lands?

**Comment by FishheadNate** [comment]
I ran across these the other day and open this issue so I could go back and take a closer look at.

The majority of the WIldlife Areas are open to hunting, but all have individual access regulations; so I think it would be best as a separate layer in the hunting collection.
- http://www.dfw.state.or.us/OARs/08.pdf

I'm not able to find a good source for the Walk In Access, so we can't add those.
