### ISSUE TITLE
Arizona GMUs - Tallying User Requests

### ISSUE THREAD

**Issue by FishheadNate** [OpenBounds/OpenHuntingData#356]
- https://gaiagpshelp.zendesk.com/agent/tickets/8085
- https://gaiagpshelp.zendesk.com/agent/tickets/15479
- https://gaiagpshelp.zendesk.com/agent/tickets/21472
- https://gaiagpshelp.zendesk.com/agent/tickets/21813

FYI: The GIS Supervisor for AZ Dept Game & Fish contacted us back in Oct
- https://gaiagpshelp.zendesk.com/agent/tickets/8383

**Comment by JesseCrocker** [comment]
Woops, looks like i forgot to flip that source to public after i added it. Now it's available, or will bei n 30 minutes.
