### ISSUE TITLE
Hunting Layers that are not displaying on gaiagps.com

### ISSUE THREAD

**Issue by FishheadNate** [OpenBounds/OpenHuntingData#380]
List order is based on the current order on gaiagps.com  
1. WY WHITE-TAILED DEER HUNT AREAS 2017
2. AK LEGISLATIVELY DESIGNATED AREAS
3. ALASKA SPECIAL HUNTING REGULATION AREAS
4. AZ GAME MANAGEMENT UNITS
5. UT ROCKY MOUNTAIN BIGHORN SHEEP HUNT UNITS 2017
6. UT MOUNTAIN GOAT HUNT UNITS 2017
7. UT ELK GENERAL SEASON SPIKE BULL UNITS 2017
8. UT WILDLIFE MANAGEMENT AREAS
9. VT WILDLIFE MANAGEMENT AREAS
10. VT WILDLIFE MANAGEMENT UNITS
11. WA GAME MANAGEMENT UNITS
12. WA GAME MANAGEMENT UNITS (duplicate)
13. WA BIGHORN SHEEP HUNT UNITS
14. WA MOOSE HUNT UNITS
15. WA MOUNTAIN GOAT UNITS
16. WA WILDLIFE AREAS
17. WI DEER MANAGEMENT METRO SUBUNITS
18. WI DEER MANAGEMENT UNITS
19. WI DEER MANAGEMENT ZONES
20. WV WILDLIFE MANAGEMENT AREAS
21. WY ANTELOPE HUNT AREAS 2017
22. WY Bighorn Sheep Hunt Areas 2017
23. WY BISON HUNT AREAS 2017
24. WY BLACK BEAR HUNT AREAS 2016
25. WY BOBCAT MANAGEMENT AREAS 2015
26. WY ELK HUNT AREAS 2017
27. WY MOOSE HUNT AREAS 2016
28. WY MOUNTAIN LION HUNT AREAS 2016
29. WY MULE DEER HUNT AREAS 2017
30. WY PHEASANT HUNT AREAS 2015
31. WY MOUNTAIN GOAT HUNT AREAS 2016
32. WY SAGE GROUSE HUNT AREAS 2016
33. WY TURKEY HUNT AREAS 2016
34. ID GMUS
35. LA WMAS & WILDLIFE REFUGES 2016
36. MA DEER UNITS
37. MI COMMERCIAL FOREST HUNTING LANDS 2017
38. WA GAME MANAGEMENT UNITS (duplicate)
39. MI HUNTER ACCESS PROGRAM LAND AREAS 2017
40. MI STATE FOREST, WILDLIFE, AND GAME AREAS OPEN TO HUNTING 2017
41. MI STATE PARKS HUNTABLE LANDS 2017
42. MI WILDLIFE MANAGEMENT UNITS
43. WI DEER MANAGEMENT ZONES (duplicate)
44. WA MOUNTAIN GOAT UNITS (duplicate)
45. WA MOOSE HUNT UNITS (duplicate)
46. MN BOBCAT, FISHER, AND MARTEN ZONES
47. MN DEER PERMIT AREAS
48. MN FURBEARER FARMLAND AND FOREST ZONES
49. MN FURBEARER ZONES
50. MN SCIENTIFIC AND NATURAL AREAS
51. MN WALK-IN ACCESS SITES 2017
52. WV WHITE-TAILED DEER HUNTING REGULATION SPLITS
53. MN WILDLIFE MANAGEMENT AREAS
54. MN WILDLIFE REFUGES
55. WA BIGHORN SHEEP HUNT UNITS (duplicate)
56. MT BIG GAME HUNTING DISTRICT RESTRICTED AREAS 2016-2017
57. MT BLOCK MANAGEMENT AREAS 2017
58. MT DEER ELK AND LION DISTRICTS 2016-2017
59. MT UPLAND GAME BIRD ENHANCEMENT PROGRAM ACCESS AREA BOUNDARIES 2017
60. MT GRAY WOLF MANAGEMENT UNITS 2016-2017
61. NV GAME MANAGEMENT UNITS (duplicate)
62. OK LAND ACCESS PROGRAM 2017
63. OK WILDLIFE MANAGEMENT UNITS
64. OR WILDLIFE MANAGEMENT UNITS
65. PA CWD MANAGEMENT UNITS 2017
66. PA ELK HUNT ZONES 2017
67. PA STATE GAME LANDS
68. PA WILDLIFE MANAGEMENT UNITS
69. TN DEER HUNTING UNITS
70. TN ELK HUNT ZONES
71. TN WILDLIFE MANAGEMENT AREAS
72. TX DOVE HUNTING ZONES
73. TX PUBLIC DOVE AND SMALL GAME HUNTING AREAS 2017-2018
74. TX WILDLIFE MANAGEMENT AREAS
75. UT ELK GENERAL SEASON ANY BULL UNITS 2017
76. UT BISON HUNT UNITS 2017
77. UT BLACK BEAR HUNT UNITS 2017
78. UT COUGAR HUNT UNITS 2017
79. UT COOPERATIVE WILDLIFE MANAGEMENT UNITS 2017
80. UT DEER GENERAL SEASON UNITS 2017
81. UT DEER LIMITED ENTRY UNITS 2017
82. UT DESERT BIGHORN HUNT UNITS 2017
83. UT ELK LIMITED ENTRY UNITS 2017
84. UT MOOSE HUNT UNITS 2017
85. UT PRONGHORN HUNT UNITS 2017

**Comment by FishheadNate** [comment]
@JesseCrocker what all information do you need to look into this?
- json file names?
- file type?
- verify url in the json file?

**Comment by JesseCrocker** [comment]
I'll look at this tomorrow

**Comment by JesseCrocker** [comment]
@FishheadNate What do you mean by not displaying? Do they not appear in the list of sources, or do tiles not show if you add the source and show it?

**Comment by FishheadNate** [comment]
tiles do not show if you add the source to the Visible section of the Layers menu

**Comment by JesseCrocker** [comment]
In the future a report that 1 or 2 sources are not working is sufficient, the same server renders all of them. No need to test all 100+ sources.

**Comment by FishheadNate** [comment]
ok, had a bit of the roof might be on fire moment

**Comment by JesseCrocker** [comment]
vector tiles were uploading to the wrong path, so they were all 404ing

**Comment by JesseCrocker** [comment]
Reuploading now, should be all fixed by tomorrow AM

**Comment by JesseCrocker** [comment]
I tried a couple of these, and they are working. They should al be working now.
