### ISSUE TITLE
Updating the file names for Walk-In layers created duplicate map sources in Admin

### ISSUE THREAD

**Issue by FishheadNate** [OpenBounds/OpenHuntingData#414]
When https://github.com/OpenBounds/OpenHuntingData/pull/413 was merged, duplicate map sources were created for all the JSON files that had their filename updated in the PR.

Example:
2017 Kansas Spring Walk-In layer was renamed from `US_KS_wiha-spring-2017` to `US_KS_spring-walk-in-2017` and now there are 2 map sources in admin for the same data
  - https://www.gaiagps.com/admin/mapsources/mapsource/?q=KS+spring+2017

Do the original map sources in admin need to be deprecated or deleted?

**Comment by JesseCrocker** [comment]
Deprecate the old ones

**Comment by FishheadNate** [comment]
Deprecated:
- https://www.gaiagps.com/admin/mapsources/mapsource/337/?_changelist_filters=o%3D1
- https://www.gaiagps.com/admin/mapsources/mapsource/367/?_changelist_filters=o%3D1
- https://www.gaiagps.com/admin/mapsources/mapsource/368/?_changelist_filters=q%3Dks
- https://www.gaiagps.com/admin/mapsources/mapsource/294/?_changelist_filters=q%3DMN
- https://www.gaiagps.com/admin/mapsources/mapsource/320/?_changelist_filters=q%3DMo
- https://www.gaiagps.com/admin/mapsources/mapsource/357/?_changelist_filters=q%3Dnd
- https://www.gaiagps.com/admin/mapsources/mapsource/362/?_changelist_filters=q%3Dne
- https://www.gaiagps.com/admin/mapsources/mapsource/256/?_changelist_filters=q%3Dok
- https://www.gaiagps.com/admin/mapsources/mapsource/267/?_changelist_filters=q%3Dtx
- https://www.gaiagps.com/admin/mapsources/mapsource/273/?_changelist_filters=q%3Dut
