### ISSUE TITLE
A bunch of Utah URLs broke

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/OpenHuntingData#426]
```
19:17:05 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_Bison.zip
19:17:06 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_SpikeElk_Gen.zip
19:17:06 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_RMBighorn.zip
19:17:07 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_CWMUs.zip
19:17:09 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_AnyBullElk_Gen.zip
19:17:09 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_Black_Bear.zip
19:17:10 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_MtGoat.zip
19:17:10 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_ElkLE.zip
19:17:11 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_AnyBullElk_Gen.zip
19:17:11 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_DeerLE.zip
19:17:12 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_DeerGen.zip
19:17:13 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_SpikeElk_Gen.zip
19:17:13 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_ElkLE.zip
19:17:14 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_DeerLE.zip
19:17:14 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_Moose.zip
19:17:15 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_RMBighorn.zip
19:17:45 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_DesBighorn.zip
19:17:45 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_Pronghorn.zip
19:18:02 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_DeerGen.zip
19:18:03 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_Black_Bear.zip
19:18:03 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_Bison.zip
19:18:04 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_Moose.zip
19:18:04 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_DesBighorn.zip
19:18:05 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_Cougar.zip
19:18:05 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_Pronghorn.zip
19:18:06 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_Cougar.zip
19:18:06 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_RMGoat.zip
```

**Comment by FishheadNate** [comment]
- [ ] 19:17:05 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_Bison.zip
- [ ] 19:17:06 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_SpikeElk_Gen.zip
- [ ] 19:17:06 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_RMBighorn.zip
- [ ] 19:17:07 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_CWMUs.zip
- [ ] 19:17:09 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_AnyBullElk_Gen.zip
- [ ] 19:17:09 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_Black_Bear.zip
- [ ] 19:17:10 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_MtGoat.zip
- [ ] 19:17:10 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_ElkLE.zip
- [ ] 19:17:11 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_AnyBullElk_Gen.zip
- [ ] 19:17:11 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_DeerLE.zip
- [ ] 19:17:12 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_DeerGen.zip
- [ ] 19:17:13 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_SpikeElk_Gen.zip
- [ ] 19:17:13 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_ElkLE.zip
- [ ] 19:17:14 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_DeerLE.zip
- [ ] 19:17:14 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_Moose.zip
- [ ] 19:17:15 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_RMBighorn.zip
- [ ] 19:17:45 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_DesBighorn.zip
- [ ] 19:17:45 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_Pronghorn.zip
- [ ] 19:18:02 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_DeerGen.zip
- [ ] 19:18:03 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_Black_Bear.zip
- [ ] 19:18:03 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_Bison.zip
- [ ] 19:18:04 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_Moose.zip
- [ ] 19:18:04 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_DesBighorn.zip
- [ ] 19:18:05 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_Cougar.zip
- [ ] 19:18:05 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_Pronghorn.zip
- [ ] 19:18:06 [ERROR] - Failed to download https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_Cougar.zip
- [ ] 19:18:06 [ERROR] - Failed to download http://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2016_RMGoat.zip

**Comment by JesseCrocker** [comment]
If it's data thats no longer current, just delete the .json file rather than fixing it

**Comment by FishheadNate** [comment]
PR #420 should fix all of this, just double checking all the files have a 2018 update

**Comment by FishheadNate** [comment]
https://dwrcdc.nr.utah.gov/ucdc/DownloadGIS/Data/Abiotic/2017_CWMUs.zip link was updated in PR https://github.com/OpenBounds/OpenHuntingData/pull/413
