### ISSUE TITLE
Add Data for Alaska

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/OpenHuntingData#61]

**Comment by backpkr1** [comment]
http://www.adfg.alaska.gov/index.cfm?adfg=huntingmaps.byspecies

**Comment by JesseCrocker** [comment]
http://adfg.maps.arcgis.com/home/item.html?id=f1019b8731aa4ec4921501d035c7ba5e

**Comment by backpkr1** [comment]
sorry I am having a hard time locating the correct kind of files, only finding PDF maps still searching

**Comment by kdough03** [comment]
Hi Anna, you may want to try searching for "state name" and "GIS". This will usually bring the state's GIS repository right up (GIS is the underlying data that's used to make the PDF maps). Then you can search for hunting in their database of GIS data (some have it under "wildlife management units").

**Comment by backpkr1** [comment]
Yes, I am finding the mxd files for the GMU's  but they do not have the individual species. The individual species I can only find are on printable pdf's just have to dig deeper to access the files they used to make those maps...

**Comment by JesseCrocker** [comment]
My impression from looking at it is that there are not separate boundaries for each species. There is one set of boundaries, but the regulations vary per-unit for each species. So the species would be listed as All.

**Comment by backpkr1** [comment]
ok Jesse should I just grab the general GMU file then? I guess I was thinking too detailed...I am searching for shape files with each game species mapped

**Comment by backpkr1** [comment]
And what is the Source Property ID and Name on the form?

**Comment by backpkr1** [comment]
I located the GMU shapefile for ALL species...
