### ISSUE TITLE
Add Data for Arizona

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/OpenHuntingData#62]

**Comment by backpkr1** [comment]
@JesseCrocker : Jesse clarification going to state websites collecting the names of all hunting areas in that state, urls for each, names of species allowed to hunt. anything else?

**Comment by JesseCrocker** [comment]
I was hoping there would be a single url for a shapefile(or some other format) with all of the districts applicable to a species in a state. If it's more than 1 file per species per state we might have to make some changes. 

For more on what specifically needs to be collected see the second half of https://github.com/OpenBounds/OpenHuntingData/blob/master/CONTRIBUTING.md

**Comment by JesseCrocker** [comment]
Basically all the information needed to fill out the form http://openbounds.github.io/OpenHuntingData/

**Comment by backpkr1** [comment]
The files are not available online, I sent in an email request
