### ISSUE TITLE
Add Data for Colorado

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/OpenHuntingData#64]

**Comment by swdgit** [comment]
My buddy Karl and I wish we would have found this db prior to me finding Gaia GPS.
I was looking at the CO data and the state updated their FTP location and added in 2016. 
Hope this helps
https://gisftp02.state.co.us/#/c.StateLevelAgencies/DNR/CPW/From/CY2016/Public/GISData/AdministrativeData/
