### ISSUE TITLE
Add Data for Connecticut

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/OpenHuntingData#65]

**Comment by kdough03** [comment]
Not available online. Will call DNREC, Wildlife Division on Monday.

**Comment by kdough03** [comment]
How to submit a file sent to me through email, since it's not available online?

**Comment by nathancahill** [comment]
I'm working on an upload features right now. Will be available soon. Hold on to the file for now.

**Comment by kdough03** [comment]
Data not available.
