### ISSUE TITLE
Add Data for New York

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/OpenHuntingData#90]

**Comment by JesseCrocker** [comment]
http://www.dec.ny.gov/maps/wmudeergoogle.kmz

**Comment by kdough03** [comment]
Wildlife Management Units (WMUs) are the geographical units DEC uses to set hunting and trapping seasons in New York State. They're only available as part of the DEC Lands and Campgrounds file at:
http://gis.ny.gov/gisdata/inventories/details.cfm?DSID=1114

Is it OK to submit that file, or should I extract them in QGIS and upload them separately?
